### PR TITLE
Add the info command to console.

### PR DESCRIPTION
**Pull request by Ccode-lang**
Thought this would be useful.  I am still adding on to this so please don't merge yet!

### CODE REVIEW

**Review by pitust — APPROVED** [review]
LGTM

**Comment by Ccode-lang** [comment]
finally

**Comment by Ccode-lang** [comment]
stupid errors

**Comment by Ccode-lang** [comment]
Should be good for merge.  Not sure if you want the url to limine in the console header or directly in the string.

**Comment by Ccode-lang** [comment]
adding it to header because it looks better.

**Review by Andy-Python-Programmer — CHANGES_REQUESTED** [review]
10 commits just to add a simple `info` command. Cherry pick or squash all of the commits into one single one.

**Comment by Ccode-lang** [comment]
How do you do that?

**Comment by Ccode-lang** [comment]
Looks like Mint can do that when merging.

**Comment by Mintsuki** [comment]
Sorry, this command seems kind of redundant and I fail to see its usefulness.

**Comment by Ccode-lang** [comment]
I thought it would be more useful when I had the idea. Sorry.

**Pull request closed without merging**
